project_id = "lhpczofddvwcyrgotzha"
auth.email.enable_confirmations = true
auth.site_url = "https://footballcoach.online"
auth.additional_redirect_urls = ["footballcoach://auth/callback", "exp+footballcoach://auth/callback", "footballcoach://auth/callback?flow=reset-password", "exp+footballcoach://auth/callback?flow=reset-password", "footballcoach://auth/recovery-callback", "exp+footballcoach://auth/recovery-callback"]
auth.email.max_frequency = "1m0s"
auth.email.otp_length = 8
auth.mfa.totp.enroll_enabled = true
auth.mfa.totp.verify_enabled = true

[auth.email.template.confirmation]
subject = "Velkommen til FootballCoach - bekr√¶ft din konto"
content_path = "./supabase/templates/confirmation.html"

[auth.email.template.recovery]
subject = "Nulstil din adgangskode"
content_path = "./supabase/templates/recovery.html"
